#ifndef MAIN_TASKS_COMMON_H_
#define MAIN_TASKS_COMMON_H_

// LED blink task
#define FEEDER_LOCAL_CONTROL_TASK_STACK_SIZE 4096
#define FEEDER_LOCAL_CONTROL_TASK_PRIORITY   4
#define FEEDER_LOCAL_CONTROL_TASK_CORE_ID    0

#endif /* MAIN_TASKS_COMMON_H_ */